# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rnorm_cpp <- function(N, mean, sd) {
    .Call('RcppDR_rnorm_cpp', PACKAGE = 'RcppDR', N, mean, sd)
}

dnorm_cpp <- function(Q, mean, sd) {
    .Call('RcppDR_dnorm_cpp', PACKAGE = 'RcppDR', Q, mean, sd)
}

g_DR_cpp <- function(dr, pd, RHO) {
    .Call('RcppDR_g_DR_cpp', PACKAGE = 'RcppDR', dr, pd, RHO)
}

rmvnorm_rcpp <- function(N, mean, sigma) {
    .Call('RcppDR_rmvnorm_rcpp', PACKAGE = 'RcppDR', N, mean, sigma)
}

dmvnorm_rcpp <- function(x, mean, sigma) {
    .Call('RcppDR_dmvnorm_rcpp', PACKAGE = 'RcppDR', x, mean, sigma)
}

tmp <- function(x) {
    .Call('RcppDR_tmp', PACKAGE = 'RcppDR', x)
}

vector_f_sum <- function(input, f) {
    .Call('RcppDR_vector_f_sum', PACKAGE = 'RcppDR', input, f)
}

